import Header from "@/components/HomePage/Header/Header";
import Footer from "@/components/HomePage/Footer";
import "./globals.css";
import ToastConfig from "./ToastifyConfig";
import StoreProvider from "./storeProvider";
import CartStorageSync from "./CartStorageSync";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function WithLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <CartStorageSync />
          <Header />
          {children}
          <ToastConfig />
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
