import "./globals.css";
import Footer from "@/components/HomePage/Footer";
import Header from "@/components/HomePage/MainHeader/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={``}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
